### ISSUE TITLE
Failed to install this role with the elao/symfony-standard

### ISSUE THREAD

**Issue by BenoitLeveque** [ElaoInfra/ansible-role-influxdb#2]
Hey guys,

i'm trying to install this role inside the elao/symfony standard box and i'm having some trouble.

i've used the configuration below (the same has the readme)

```
elao_influxdb_config:
    elao_influxdb_databases:
      - statsd

    elao_influxdb_users:
     - { database: statsd, name: my_user, password: my_suer }

    elao_influxdb_privileges:
     - { database: statsd, user: my_user, grant: ALL }
```

When i launch the provisionning of my vagrant i have the following issue :

```
fatal: [default] => One or more undefined variables: 'unicode object' has no attribute 'database'
```
